name: Socket CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install boost
      run: sudo apt install -y libboost-dev

    - name: Clone sourcemod
      run: |
        mkdir -p alliedmodders
        cd alliedmodders
        git clone --recursive https://github.com/alliedmodders/sourcemod

    - name: Execute checkout-deps.sh
      run: |
        cd alliedmodders
        bash sourcemod/tools/checkout-deps.sh
    
    - name: Configure
      run: |
        CC=clang CXX=clang++ python configure.py --enable-optimize --hl2sdk-root='alliedmodders/' --mms-path='alliedmodders/mmsource-1.10/' --sm-path='alliedmodders/sourcemod/'
    
    - name: Build
      run: ambuild
